### ISSUE TITLE
Possible Mojave QT issues with SlicerNotebooks

### ISSUE THREAD

**Issue by hjmjohnson** [Slicer/SlicerNotebooks#3]
![image](https://user-images.githubusercontent.com/313970/52179053-2115c600-279b-11e9-97b4-2c49d937426e.png)

**Comment by lassoan** [comment]
We hide the sliders, this is a feature.

**Comment by hjmjohnson** [comment]
Oh.  I was trying to replicate what is shown on https://github.com/Slicer/SlicerNotebooks/blob/master/01_Data_Loading_and_Visualization.ipynb

Can they be turned back on easily?  I need the sliders to work for allowing quick reviews of data.

**Comment by hjmjohnson** [comment]
I'm closing.  I think I mis-understood how this was working.  I thought that the sliders would work from jupyter notebook to update the display.  I think that was "display()" does is take a snapshot of the current slicer interface.

I would need to separately program a slice change from python and re-render.

**Comment by lassoan** [comment]
Yes, these are static screenshots. You can switch to the launched Slicer instance for interactive data exploration (both the application and the Jupyter kernel are available for interactive use at the same time) and we'll are also considering adding ITK Jupyter widgets.
